/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as TournamentRouteImport } from './routes/tournament'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SelectTeamsForMatchRouteImport } from './routes/select-teams-for-match'
import { Route as MatchRouteImport } from './routes/match'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CreateTournamentRouteRouteImport } from './routes/create-tournament/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateTournamentIndexRouteImport } from './routes/create-tournament/index'
import { Route as CreateTournamentTournamentIdCreatedRouteImport } from './routes/create-tournament/$tournamentId/created'
import { Route as CreateTournamentTournamentIdCreateDrawRouteImport } from './routes/create-tournament/$tournamentId/create-draw'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentRoute = TournamentRouteImport.update({
  id: '/tournament',
  path: '/tournament',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectTeamsForMatchRoute = SelectTeamsForMatchRouteImport.update({
  id: '/select-teams-for-match',
  path: '/select-teams-for-match',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateTournamentRouteRoute = CreateTournamentRouteRouteImport.update({
  id: '/create-tournament',
  path: '/create-tournament',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateTournamentIndexRoute = CreateTournamentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreateTournamentRouteRoute,
} as any)
const CreateTournamentTournamentIdCreatedRoute =
  CreateTournamentTournamentIdCreatedRouteImport.update({
    id: '/$tournamentId/created',
    path: '/$tournamentId/created',
    getParentRoute: () => CreateTournamentRouteRoute,
  } as any)
const CreateTournamentTournamentIdCreateDrawRoute =
  CreateTournamentTournamentIdCreateDrawRouteImport.update({
    id: '/$tournamentId/create-draw',
    path: '/$tournamentId/create-draw',
    getParentRoute: () => CreateTournamentRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-tournament': typeof CreateTournamentRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/match': typeof MatchRoute
  '/select-teams-for-match': typeof SelectTeamsForMatchRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/tournament': typeof TournamentRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/create-tournament/': typeof CreateTournamentIndexRoute
  '/create-tournament/$tournamentId/create-draw': typeof CreateTournamentTournamentIdCreateDrawRoute
  '/create-tournament/$tournamentId/created': typeof CreateTournamentTournamentIdCreatedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/match': typeof MatchRoute
  '/select-teams-for-match': typeof SelectTeamsForMatchRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/tournament': typeof TournamentRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/create-tournament': typeof CreateTournamentIndexRoute
  '/create-tournament/$tournamentId/create-draw': typeof CreateTournamentTournamentIdCreateDrawRoute
  '/create-tournament/$tournamentId/created': typeof CreateTournamentTournamentIdCreatedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-tournament': typeof CreateTournamentRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/match': typeof MatchRoute
  '/select-teams-for-match': typeof SelectTeamsForMatchRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/tournament': typeof TournamentRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/create-tournament/': typeof CreateTournamentIndexRoute
  '/create-tournament/$tournamentId/create-draw': typeof CreateTournamentTournamentIdCreateDrawRoute
  '/create-tournament/$tournamentId/created': typeof CreateTournamentTournamentIdCreatedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-tournament'
    | '/forgot-password'
    | '/match'
    | '/select-teams-for-match'
    | '/signin'
    | '/signup'
    | '/tournament'
    | '/verify-otp'
    | '/create-tournament/'
    | '/create-tournament/$tournamentId/create-draw'
    | '/create-tournament/$tournamentId/created'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/match'
    | '/select-teams-for-match'
    | '/signin'
    | '/signup'
    | '/tournament'
    | '/verify-otp'
    | '/create-tournament'
    | '/create-tournament/$tournamentId/create-draw'
    | '/create-tournament/$tournamentId/created'
  id:
    | '__root__'
    | '/'
    | '/create-tournament'
    | '/forgot-password'
    | '/match'
    | '/select-teams-for-match'
    | '/signin'
    | '/signup'
    | '/tournament'
    | '/verify-otp'
    | '/create-tournament/'
    | '/create-tournament/$tournamentId/create-draw'
    | '/create-tournament/$tournamentId/created'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateTournamentRouteRoute: typeof CreateTournamentRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  MatchRoute: typeof MatchRoute
  SelectTeamsForMatchRoute: typeof SelectTeamsForMatchRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  TournamentRoute: typeof TournamentRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament': {
      id: '/tournament'
      path: '/tournament'
      fullPath: '/tournament'
      preLoaderRoute: typeof TournamentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-teams-for-match': {
      id: '/select-teams-for-match'
      path: '/select-teams-for-match'
      fullPath: '/select-teams-for-match'
      preLoaderRoute: typeof SelectTeamsForMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-tournament': {
      id: '/create-tournament'
      path: '/create-tournament'
      fullPath: '/create-tournament'
      preLoaderRoute: typeof CreateTournamentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-tournament/': {
      id: '/create-tournament/'
      path: '/'
      fullPath: '/create-tournament/'
      preLoaderRoute: typeof CreateTournamentIndexRouteImport
      parentRoute: typeof CreateTournamentRouteRoute
    }
    '/create-tournament/$tournamentId/created': {
      id: '/create-tournament/$tournamentId/created'
      path: '/$tournamentId/created'
      fullPath: '/create-tournament/$tournamentId/created'
      preLoaderRoute: typeof CreateTournamentTournamentIdCreatedRouteImport
      parentRoute: typeof CreateTournamentRouteRoute
    }
    '/create-tournament/$tournamentId/create-draw': {
      id: '/create-tournament/$tournamentId/create-draw'
      path: '/$tournamentId/create-draw'
      fullPath: '/create-tournament/$tournamentId/create-draw'
      preLoaderRoute: typeof CreateTournamentTournamentIdCreateDrawRouteImport
      parentRoute: typeof CreateTournamentRouteRoute
    }
  }
}

interface CreateTournamentRouteRouteChildren {
  CreateTournamentIndexRoute: typeof CreateTournamentIndexRoute
  CreateTournamentTournamentIdCreateDrawRoute: typeof CreateTournamentTournamentIdCreateDrawRoute
  CreateTournamentTournamentIdCreatedRoute: typeof CreateTournamentTournamentIdCreatedRoute
}

const CreateTournamentRouteRouteChildren: CreateTournamentRouteRouteChildren = {
  CreateTournamentIndexRoute: CreateTournamentIndexRoute,
  CreateTournamentTournamentIdCreateDrawRoute:
    CreateTournamentTournamentIdCreateDrawRoute,
  CreateTournamentTournamentIdCreatedRoute:
    CreateTournamentTournamentIdCreatedRoute,
}

const CreateTournamentRouteRouteWithChildren =
  CreateTournamentRouteRoute._addFileChildren(
    CreateTournamentRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateTournamentRouteRoute: CreateTournamentRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  MatchRoute: MatchRoute,
  SelectTeamsForMatchRoute: SelectTeamsForMatchRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  TournamentRoute: TournamentRoute,
  VerifyOtpRoute: VerifyOtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
