/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as TournamentStatsRouteImport } from './routes/tournament-stats'
import { Route as TournamentRouteImport } from './routes/tournament'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SelectTeamsForMatchRouteImport } from './routes/select-teams-for-match'
import { Route as MatchRouteImport } from './routes/match'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as CreateTournamentRouteRouteImport } from './routes/create-tournament/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CreateTournamentIndexRouteImport } from './routes/create-tournament/index'
import { Route as DashboardTournamentsRouteImport } from './routes/dashboard/tournaments'
import { Route as DashboardManageCricketRouteImport } from './routes/dashboard/manage-cricket'
import { Route as DashboardCreateClubRouteImport } from './routes/dashboard/create-club'
import { Route as DashboardContactUsRouteImport } from './routes/dashboard/contact-us'
import { Route as CreateTournamentTournamentIdTeamsRouteImport } from './routes/create-tournament/$tournamentId/teams'
import { Route as CreateTournamentTournamentIdOfficialsRouteImport } from './routes/create-tournament/$tournamentId/officials'
import { Route as CreateTournamentTournamentIdGroundsRouteImport } from './routes/create-tournament/$tournamentId/grounds'
import { Route as CreateTournamentTournamentIdCreatedRouteImport } from './routes/create-tournament/$tournamentId/created'
import { Route as CreateTournamentTournamentIdCreateDrawRouteImport } from './routes/create-tournament/$tournamentId/create-draw'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentStatsRoute = TournamentStatsRouteImport.update({
  id: '/tournament-stats',
  path: '/tournament-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentRoute = TournamentRouteImport.update({
  id: '/tournament',
  path: '/tournament',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectTeamsForMatchRoute = SelectTeamsForMatchRouteImport.update({
  id: '/select-teams-for-match',
  path: '/select-teams-for-match',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateTournamentRouteRoute = CreateTournamentRouteRouteImport.update({
  id: '/create-tournament',
  path: '/create-tournament',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const CreateTournamentIndexRoute = CreateTournamentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreateTournamentRouteRoute,
} as any)
const DashboardTournamentsRoute = DashboardTournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardManageCricketRoute = DashboardManageCricketRouteImport.update({
  id: '/manage-cricket',
  path: '/manage-cricket',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCreateClubRoute = DashboardCreateClubRouteImport.update({
  id: '/create-club',
  path: '/create-club',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardContactUsRoute = DashboardContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const CreateTournamentTournamentIdTeamsRoute =
  CreateTournamentTournamentIdTeamsRouteImport.update({
    id: '/$tournamentId/teams',
    path: '/$tournamentId/teams',
    getParentRoute: () => CreateTournamentRouteRoute,
  } as any)
const CreateTournamentTournamentIdOfficialsRoute =
  CreateTournamentTournamentIdOfficialsRouteImport.update({
    id: '/$tournamentId/officials',
    path: '/$tournamentId/officials',
    getParentRoute: () => CreateTournamentRouteRoute,
  } as any)
const CreateTournamentTournamentIdGroundsRoute =
  CreateTournamentTournamentIdGroundsRouteImport.update({
    id: '/$tournamentId/grounds',
    path: '/$tournamentId/grounds',
    getParentRoute: () => CreateTournamentRouteRoute,
  } as any)
const CreateTournamentTournamentIdCreatedRoute =
  CreateTournamentTournamentIdCreatedRouteImport.update({
    id: '/$tournamentId/created',
    path: '/$tournamentId/created',
    getParentRoute: () => CreateTournamentRouteRoute,
  } as any)
const CreateTournamentTournamentIdCreateDrawRoute =
  CreateTournamentTournamentIdCreateDrawRouteImport.update({
    id: '/$tournamentId/create-draw',
    path: '/$tournamentId/create-draw',
    getParentRoute: () => CreateTournamentRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-tournament': typeof CreateTournamentRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/match': typeof MatchRoute
  '/select-teams-for-match': typeof SelectTeamsForMatchRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/tournament': typeof TournamentRoute
  '/tournament-stats': typeof TournamentStatsRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/dashboard/contact-us': typeof DashboardContactUsRoute
  '/dashboard/create-club': typeof DashboardCreateClubRoute
  '/dashboard/manage-cricket': typeof DashboardManageCricketRoute
  '/dashboard/tournaments': typeof DashboardTournamentsRoute
  '/create-tournament/': typeof CreateTournamentIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/create-tournament/$tournamentId/create-draw': typeof CreateTournamentTournamentIdCreateDrawRoute
  '/create-tournament/$tournamentId/created': typeof CreateTournamentTournamentIdCreatedRoute
  '/create-tournament/$tournamentId/grounds': typeof CreateTournamentTournamentIdGroundsRoute
  '/create-tournament/$tournamentId/officials': typeof CreateTournamentTournamentIdOfficialsRoute
  '/create-tournament/$tournamentId/teams': typeof CreateTournamentTournamentIdTeamsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/match': typeof MatchRoute
  '/select-teams-for-match': typeof SelectTeamsForMatchRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/tournament': typeof TournamentRoute
  '/tournament-stats': typeof TournamentStatsRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/dashboard/contact-us': typeof DashboardContactUsRoute
  '/dashboard/create-club': typeof DashboardCreateClubRoute
  '/dashboard/manage-cricket': typeof DashboardManageCricketRoute
  '/dashboard/tournaments': typeof DashboardTournamentsRoute
  '/create-tournament': typeof CreateTournamentIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/create-tournament/$tournamentId/create-draw': typeof CreateTournamentTournamentIdCreateDrawRoute
  '/create-tournament/$tournamentId/created': typeof CreateTournamentTournamentIdCreatedRoute
  '/create-tournament/$tournamentId/grounds': typeof CreateTournamentTournamentIdGroundsRoute
  '/create-tournament/$tournamentId/officials': typeof CreateTournamentTournamentIdOfficialsRoute
  '/create-tournament/$tournamentId/teams': typeof CreateTournamentTournamentIdTeamsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-tournament': typeof CreateTournamentRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/match': typeof MatchRoute
  '/select-teams-for-match': typeof SelectTeamsForMatchRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/tournament': typeof TournamentRoute
  '/tournament-stats': typeof TournamentStatsRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/dashboard/contact-us': typeof DashboardContactUsRoute
  '/dashboard/create-club': typeof DashboardCreateClubRoute
  '/dashboard/manage-cricket': typeof DashboardManageCricketRoute
  '/dashboard/tournaments': typeof DashboardTournamentsRoute
  '/create-tournament/': typeof CreateTournamentIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/create-tournament/$tournamentId/create-draw': typeof CreateTournamentTournamentIdCreateDrawRoute
  '/create-tournament/$tournamentId/created': typeof CreateTournamentTournamentIdCreatedRoute
  '/create-tournament/$tournamentId/grounds': typeof CreateTournamentTournamentIdGroundsRoute
  '/create-tournament/$tournamentId/officials': typeof CreateTournamentTournamentIdOfficialsRoute
  '/create-tournament/$tournamentId/teams': typeof CreateTournamentTournamentIdTeamsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-tournament'
    | '/dashboard'
    | '/forgot-password'
    | '/match'
    | '/select-teams-for-match'
    | '/signin'
    | '/signup'
    | '/tournament'
    | '/tournament-stats'
    | '/verify-otp'
    | '/dashboard/contact-us'
    | '/dashboard/create-club'
    | '/dashboard/manage-cricket'
    | '/dashboard/tournaments'
    | '/create-tournament/'
    | '/dashboard/'
    | '/create-tournament/$tournamentId/create-draw'
    | '/create-tournament/$tournamentId/created'
    | '/create-tournament/$tournamentId/grounds'
    | '/create-tournament/$tournamentId/officials'
    | '/create-tournament/$tournamentId/teams'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/match'
    | '/select-teams-for-match'
    | '/signin'
    | '/signup'
    | '/tournament'
    | '/tournament-stats'
    | '/verify-otp'
    | '/dashboard/contact-us'
    | '/dashboard/create-club'
    | '/dashboard/manage-cricket'
    | '/dashboard/tournaments'
    | '/create-tournament'
    | '/dashboard'
    | '/create-tournament/$tournamentId/create-draw'
    | '/create-tournament/$tournamentId/created'
    | '/create-tournament/$tournamentId/grounds'
    | '/create-tournament/$tournamentId/officials'
    | '/create-tournament/$tournamentId/teams'
  id:
    | '__root__'
    | '/'
    | '/create-tournament'
    | '/dashboard'
    | '/forgot-password'
    | '/match'
    | '/select-teams-for-match'
    | '/signin'
    | '/signup'
    | '/tournament'
    | '/tournament-stats'
    | '/verify-otp'
    | '/dashboard/contact-us'
    | '/dashboard/create-club'
    | '/dashboard/manage-cricket'
    | '/dashboard/tournaments'
    | '/create-tournament/'
    | '/dashboard/'
    | '/create-tournament/$tournamentId/create-draw'
    | '/create-tournament/$tournamentId/created'
    | '/create-tournament/$tournamentId/grounds'
    | '/create-tournament/$tournamentId/officials'
    | '/create-tournament/$tournamentId/teams'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateTournamentRouteRoute: typeof CreateTournamentRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  MatchRoute: typeof MatchRoute
  SelectTeamsForMatchRoute: typeof SelectTeamsForMatchRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  TournamentRoute: typeof TournamentRoute
  TournamentStatsRoute: typeof TournamentStatsRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament-stats': {
      id: '/tournament-stats'
      path: '/tournament-stats'
      fullPath: '/tournament-stats'
      preLoaderRoute: typeof TournamentStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament': {
      id: '/tournament'
      path: '/tournament'
      fullPath: '/tournament'
      preLoaderRoute: typeof TournamentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-teams-for-match': {
      id: '/select-teams-for-match'
      path: '/select-teams-for-match'
      fullPath: '/select-teams-for-match'
      preLoaderRoute: typeof SelectTeamsForMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-tournament': {
      id: '/create-tournament'
      path: '/create-tournament'
      fullPath: '/create-tournament'
      preLoaderRoute: typeof CreateTournamentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/create-tournament/': {
      id: '/create-tournament/'
      path: '/'
      fullPath: '/create-tournament/'
      preLoaderRoute: typeof CreateTournamentIndexRouteImport
      parentRoute: typeof CreateTournamentRouteRoute
    }
    '/dashboard/tournaments': {
      id: '/dashboard/tournaments'
      path: '/tournaments'
      fullPath: '/dashboard/tournaments'
      preLoaderRoute: typeof DashboardTournamentsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/manage-cricket': {
      id: '/dashboard/manage-cricket'
      path: '/manage-cricket'
      fullPath: '/dashboard/manage-cricket'
      preLoaderRoute: typeof DashboardManageCricketRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/create-club': {
      id: '/dashboard/create-club'
      path: '/create-club'
      fullPath: '/dashboard/create-club'
      preLoaderRoute: typeof DashboardCreateClubRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/contact-us': {
      id: '/dashboard/contact-us'
      path: '/contact-us'
      fullPath: '/dashboard/contact-us'
      preLoaderRoute: typeof DashboardContactUsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/create-tournament/$tournamentId/teams': {
      id: '/create-tournament/$tournamentId/teams'
      path: '/$tournamentId/teams'
      fullPath: '/create-tournament/$tournamentId/teams'
      preLoaderRoute: typeof CreateTournamentTournamentIdTeamsRouteImport
      parentRoute: typeof CreateTournamentRouteRoute
    }
    '/create-tournament/$tournamentId/officials': {
      id: '/create-tournament/$tournamentId/officials'
      path: '/$tournamentId/officials'
      fullPath: '/create-tournament/$tournamentId/officials'
      preLoaderRoute: typeof CreateTournamentTournamentIdOfficialsRouteImport
      parentRoute: typeof CreateTournamentRouteRoute
    }
    '/create-tournament/$tournamentId/grounds': {
      id: '/create-tournament/$tournamentId/grounds'
      path: '/$tournamentId/grounds'
      fullPath: '/create-tournament/$tournamentId/grounds'
      preLoaderRoute: typeof CreateTournamentTournamentIdGroundsRouteImport
      parentRoute: typeof CreateTournamentRouteRoute
    }
    '/create-tournament/$tournamentId/created': {
      id: '/create-tournament/$tournamentId/created'
      path: '/$tournamentId/created'
      fullPath: '/create-tournament/$tournamentId/created'
      preLoaderRoute: typeof CreateTournamentTournamentIdCreatedRouteImport
      parentRoute: typeof CreateTournamentRouteRoute
    }
    '/create-tournament/$tournamentId/create-draw': {
      id: '/create-tournament/$tournamentId/create-draw'
      path: '/$tournamentId/create-draw'
      fullPath: '/create-tournament/$tournamentId/create-draw'
      preLoaderRoute: typeof CreateTournamentTournamentIdCreateDrawRouteImport
      parentRoute: typeof CreateTournamentRouteRoute
    }
  }
}

interface CreateTournamentRouteRouteChildren {
  CreateTournamentIndexRoute: typeof CreateTournamentIndexRoute
  CreateTournamentTournamentIdCreateDrawRoute: typeof CreateTournamentTournamentIdCreateDrawRoute
  CreateTournamentTournamentIdCreatedRoute: typeof CreateTournamentTournamentIdCreatedRoute
  CreateTournamentTournamentIdGroundsRoute: typeof CreateTournamentTournamentIdGroundsRoute
  CreateTournamentTournamentIdOfficialsRoute: typeof CreateTournamentTournamentIdOfficialsRoute
  CreateTournamentTournamentIdTeamsRoute: typeof CreateTournamentTournamentIdTeamsRoute
}

const CreateTournamentRouteRouteChildren: CreateTournamentRouteRouteChildren = {
  CreateTournamentIndexRoute: CreateTournamentIndexRoute,
  CreateTournamentTournamentIdCreateDrawRoute:
    CreateTournamentTournamentIdCreateDrawRoute,
  CreateTournamentTournamentIdCreatedRoute:
    CreateTournamentTournamentIdCreatedRoute,
  CreateTournamentTournamentIdGroundsRoute:
    CreateTournamentTournamentIdGroundsRoute,
  CreateTournamentTournamentIdOfficialsRoute:
    CreateTournamentTournamentIdOfficialsRoute,
  CreateTournamentTournamentIdTeamsRoute:
    CreateTournamentTournamentIdTeamsRoute,
}

const CreateTournamentRouteRouteWithChildren =
  CreateTournamentRouteRoute._addFileChildren(
    CreateTournamentRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardContactUsRoute: typeof DashboardContactUsRoute
  DashboardCreateClubRoute: typeof DashboardCreateClubRoute
  DashboardManageCricketRoute: typeof DashboardManageCricketRoute
  DashboardTournamentsRoute: typeof DashboardTournamentsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardContactUsRoute: DashboardContactUsRoute,
  DashboardCreateClubRoute: DashboardCreateClubRoute,
  DashboardManageCricketRoute: DashboardManageCricketRoute,
  DashboardTournamentsRoute: DashboardTournamentsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateTournamentRouteRoute: CreateTournamentRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  MatchRoute: MatchRoute,
  SelectTeamsForMatchRoute: SelectTeamsForMatchRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  TournamentRoute: TournamentRoute,
  TournamentStatsRoute: TournamentStatsRoute,
  VerifyOtpRoute: VerifyOtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
